[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[dev]
  command = "npm run dev"
  targetPort = 3333
  autoLaunch = true